Squashed 'external/devlib/' changes from 17d4b22b9f0c..e01a76ef1bf5
e01a76ef1bf5 doc: Explain the 'tar' flag of target.read_tree_values
9fcca2503127 hwmon: Robustify hwmon scan
a6b9542f0f8c target: Speed-up read_tree_values()
413e83f5d632 target/kernelconfig: Add alias for itteritems
ac1987342328 target/TypedKernelConfig: Fix converting to string method

git-subtree-dir: external/devlib
git-subtree-split: e01a76ef1bf5a9f221136198f27233d2308a320b

diff --git a/devlib/bin/scripts/shutils.in b/devlib/bin/scripts/shutils.in
--- a/devlib/bin/scripts/shutils.in
+++ b/devlib/bin/scripts/shutils.in
@@ -255,6 +255,28 @@ sched_get_kernel_attributes() {
 # Misc
 ################################################################################
 
+read_tree_values() {
+    BASEPATH=$1
+    MAXDEPTH=$2
+
+    if [ ! -e $BASEPATH ]; then
+        echo "ERROR: $BASEPATH does not exist"
+        exit 1
+    fi
+
+    PATHS=$($BUSYBOX find $BASEPATH -follow -maxdepth $MAXDEPTH)
+    i=0
+    for path in $PATHS; do
+        i=$(expr $i + 1)
+        if [ $i -gt 1 ]; then
+            break;
+        fi
+    done
+    if [ $i -gt 1 ]; then
+        $BUSYBOX grep -s '' $PATHS
+    fi
+}
+
 read_tree_tgz_b64() {
     BASEPATH=$1
     MAXDEPTH=$2
@@ -352,6 +374,9 @@ ftrace_get_function_stats)
     ;;
 hotplug_online_all)
 	hotplug_online_all
+    ;;
+read_tree_values)
+	read_tree_values $*
     ;;
 read_tree_tgz_b64)
 	read_tree_tgz_b64 $*
