Fix LISA-shell paths
lisa-help only works when called from the LISA root folder. Fix this by
storing LISA_HOME correctly and add a useful error message if someone
tries to initialize the LISA-shell outside the LISA root folder.

Signed-off-by: Morten Rasmussen <morten.rasmussen@arm.com>

diff --git a/init_env b/init_env
--- a/init_env
+++ b/init_env
@@ -20,6 +20,9 @@
 grep "bash" /proc/$$/cmdline &>/dev/null
 if [ $? -eq 0 ]; then
 	source ./src/shell/lisa_shell
+	if [ ! $? -eq 0 ]; then
+	echo "ERROR: LISA must be initialized from the LISA home folder."
+	fi
 else
 	echo "WARNING: Current shell is not a BASH"
 	# Check if a bash shell is available
